const truffleProvider = require("truffle-hdwallet-provider");
const Web3 = require("web3");

const compiledFactory = require('../build/Factory.json');

const provider = new truffleProvider(
    // "12 random words generated by meta mask for your account",
    // infura provider api
);

const web3 = new Web3(provider);

const deploy = async () => {
    const accounts = await web3.eth.getAccounts();
    const result = await new web3.eth.Contract(JSON.parse(compiledFactory.interface))
        .deploy({ data: compiledFactory.bytecode })
        .send({ from: accounts[0], gas: "1000000" });
};

deploy();
